### ISSUE TITLE
Not Giving A weapon with when using esx_inventoryhud

### ISSUE THREAD

**Issue by trclassic92** [qalle-fivem/esx_hunting#15]
Currently having a issue with the players getting the weapon because I use this inventory menu

Any suggestions on how I can fix this problem?

**Comment by bitpredator** [comment]
> Currently having a issue with the players getting the weapon because I use this inventory menu
> 
> Any suggestions on how I can fix this problem?



Remove strings 170 and 171 in client / main.lua

--	GiveWeaponToPed(PlayerPedId(), GetHashKey("WEAPON_HEAVYSNIPER"),45, true, false)
--	GiveWeaponToPed(PlayerPedId(), GetHashKey("WEAPON_KNIFE"),0, true, false)
